name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: sudo apt install -y gcc make
      
      - name: Build and Run
        run: |
          cd examples
          make
          cd build
          ./main && (echo "Failed to execute ./main"; exit 1) || (exit 0)


  test_extern:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: sudo apt install -y gcc make

      - name: Build and Run
        run: |
          cd examples
          make
          make external_module
          cd build
          ./main external_module.so

